"""Focused public entrypoints for connector adapters and source definitions."""

from alma_connectors.adapters.airflow import AirflowAdapter
from alma_connectors.adapters.bigquery import BigQueryAdapter
from alma_connectors.adapters.dbt import DbtAdapter
from alma_connectors.adapters.fivetran import FivetranAdapter
from alma_connectors.adapters.looker import LookerAdapter
from alma_connectors.adapters.metabase import MetabaseAdapter
from alma_connectors.adapters.postgres import PostgresAdapter
from alma_connectors.adapters.snowflake import SnowflakeAdapter
from alma_connectors.adapters.sqlite import SQLiteAdapter
from alma_connectors.catalog import (
    CONNECTOR_SPECS,
    SUPPORTED_SOURCE_KINDS,
    ConnectorSpec,
    get_connector_spec,
    get_setup_instructions,
)
from alma_connectors.definition_codec import (
    build_adapter_definition,
    build_persisted_adapter,
    deserialize_config,
    serialize_definition,
)
from alma_connectors.source_adapter import (
    AirflowAdapterConfig,
    BigQueryAdapterConfig,
    ConnectionTestResult,
    DbtAdapterConfig,
    ExternalSecretRef,
    FivetranAdapterConfig,
    LookerAdapterConfig,
    ManagedSecret,
    MetabaseAdapterConfig,
    ObservedQueryEvent,
    PersistedSourceAdapter,
    PostgresAdapterConfig,
    PostgresLogCaptureConfig,
    PostgresReadReplicaConfig,
    QueryResult,
    SchemaObjectKind,
    SchemaSnapshot,
    SetupInstructions,
    SnowflakeAdapterConfig,
    SourceAdapterCapabilities,
    SourceAdapterDefinition,
    SourceAdapterKind,
    SourceAdapterProbeRoutingOverride,
    SourceAdapterStatus,
    SourceColumnSchema,
    SourceObjectDependency,
    SourceTableSchema,
    SQLiteAdapterConfig,
    TrafficObservationResult,
    apply_probe_routing_override,
    normalize_source_adapter_key,
    resolve_probe_target,
)
from alma_connectors.source_adapter_runtime import RuntimeSourceAdapter, instantiate_runtime_adapter
from alma_connectors.source_adapter_service import SourceAdapterService

__all__ = [
    "AirflowAdapter",
    "AirflowAdapterConfig",
    "BigQueryAdapter",
    "BigQueryAdapterConfig",
    "ConnectionTestResult",
    "CONNECTOR_SPECS",
    "ConnectorSpec",
    "DbtAdapter",
    "DbtAdapterConfig",
    "ExternalSecretRef",
    "FivetranAdapter",
    "FivetranAdapterConfig",
    "LookerAdapter",
    "LookerAdapterConfig",
    "ManagedSecret",
    "MetabaseAdapter",
    "MetabaseAdapterConfig",
    "ObservedQueryEvent",
    "PersistedSourceAdapter",
    "PostgresAdapter",
    "PostgresAdapterConfig",
    "PostgresLogCaptureConfig",
    "PostgresReadReplicaConfig",
    "QueryResult",
    "RuntimeSourceAdapter",
    "SUPPORTED_SOURCE_KINDS",
    "SchemaObjectKind",
    "SchemaSnapshot",
    "SetupInstructions",
    "SQLiteAdapter",
    "SQLiteAdapterConfig",
    "SnowflakeAdapter",
    "SnowflakeAdapterConfig",
    "SourceAdapterCapabilities",
    "SourceAdapterDefinition",
    "SourceAdapterKind",
    "SourceAdapterProbeRoutingOverride",
    "SourceAdapterService",
    "SourceAdapterStatus",
    "SourceColumnSchema",
    "SourceObjectDependency",
    "SourceTableSchema",
    "TrafficObservationResult",
    "apply_probe_routing_override",
    "build_adapter_definition",
    "build_persisted_adapter",
    "deserialize_config",
    "get_connector_spec",
    "get_setup_instructions",
    "instantiate_runtime_adapter",
    "normalize_source_adapter_key",
    "resolve_probe_target",
    "serialize_definition",
]
