"""Core relational algebra models."""

from alma_algebrakit.models.algebra import (
    AggregateFunction,
    AggregateSpec,
    Aggregation,
    AtomicPredicate,
    BinaryExpression,
    BoundColumnRef,
    CaseExpression,
    ColumnRef,
    ComparisonOp,
    CompoundPredicate,
    CTEDefinition,
    Difference,
    ExistsExpression,
    Expression,
    FunctionCall,
    InSubqueryExpression,
    Intersect,
    Join,
    JoinType,
    Limit,
    Literal,
    LogicalOp,
    NullsPosition,
    Predicate,
    Projection,
    RAExpression,
    Relation,
    RelationRef,
    Selection,
    Sort,
    SortDirection,
    SortSpec,
    SubqueryExpression,
    Union,
    WindowExpression,
    WindowFrameBound,
    WindowFrameSpec,
    WindowFrameType,
    WindowSpec,
    WithExpression,
    build_alias_map,
    check_for_self_joins,
    resolve_column_to_relation,
)
from alma_algebrakit.models.capabilities import (
    REWRITE_REQUIREMENTS,
    DeterminismLevel,
    NullMode,
    QueryCapabilities,
    SemanticsMode,
    SQLFeature,
    check_rewrite_compatibility,
)

__all__ = [
    # RA Expressions
    "RAExpression",
    "Relation",
    "Selection",
    "Projection",
    "Join",
    "Aggregation",
    "Union",
    "Difference",
    "Intersect",
    "Sort",
    "SortSpec",
    "Limit",
    "WithExpression",
    "CTEDefinition",
    # Predicates
    "Predicate",
    "AtomicPredicate",
    "CompoundPredicate",
    # Expressions
    "Expression",
    "ColumnRef",
    "Literal",
    "BinaryExpression",
    "FunctionCall",
    "WindowFrameSpec",
    "WindowSpec",
    "WindowExpression",
    "CaseExpression",
    "SubqueryExpression",
    "ExistsExpression",
    "InSubqueryExpression",
    # Specs
    "AggregateSpec",
    # Enums
    "JoinType",
    "ComparisonOp",
    "LogicalOp",
    "AggregateFunction",
    "SortDirection",
    "NullsPosition",
    "WindowFrameType",
    "WindowFrameBound",
    # Relation Identity
    "RelationRef",
    "BoundColumnRef",
    # Utility Functions
    "build_alias_map",
    "resolve_column_to_relation",
    "check_for_self_joins",
    # Capabilities
    "QueryCapabilities",
    "SQLFeature",
    "SemanticsMode",
    "NullMode",
    "DeterminismLevel",
    "REWRITE_REQUIREMENTS",
    "check_rewrite_compatibility",
]
